"""Change PostCategory name on unique

Revision ID: c13bfa53bb23
Revises: 6d5cc16bdbf8
Create Date: 2024-11-30 11:41:39.264017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c13bfa53bb23'
down_revision: Union[str, None] = '6d5cc16bdbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blacklisted_tokens_id', table_name='blacklisted_tokens')
    op.drop_index('ix_blacklisted_tokens_jti', table_name='blacklisted_tokens')
    op.drop_index('ix_blacklisted_tokens_token', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    op.drop_index('ix_revoked_tokens_id', table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_token', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.alter_column('categories', 'category_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'categories', ['category_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.alter_column('categories', 'category_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='revoked_tokens_pkey')
    )
    op.create_index('ix_revoked_tokens_token', 'revoked_tokens', ['token'], unique=True)
    op.create_index('ix_revoked_tokens_id', 'revoked_tokens', ['id'], unique=False)
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blacklisted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blacklisted_tokens_pkey')
    )
    op.create_index('ix_blacklisted_tokens_token', 'blacklisted_tokens', ['token'], unique=True)
    op.create_index('ix_blacklisted_tokens_jti', 'blacklisted_tokens', ['jti'], unique=True)
    op.create_index('ix_blacklisted_tokens_id', 'blacklisted_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
